binop_separator  = "Back"
wrap_comments = true
fn_args_density = "Tall"
brace_style = "PreferSameLine"
empty_item_single_line = true
fn_single_line = true
format_strings = true
format_macro_matchers = true
hard_tabs = true
imports_layout = "HorizontalVertical"
merge_imports = true
max_width = 100
newline_style = "Unix"
normalize_comments = true
reorder_impl_items = true
report_todo = "Always"
report_fixme = "Always"
tab_spaces = 4
trailing_semicolon = true
use_try_shorthand = true
format_doc_comments = true
edition = "2018"
normalize_doc_attributes = true
