[package]
name = "orion"
version = "0.1.0"
authors = ["brycx <brycx@protonmail.com>"]
description = "Hassle-free Rust crypto."
keywords = [ "cryptography", "hmac" ]
readme = "README.md"
repository = "https://github.com/brycx/orion"
license-file = "LICENSE"

[dependencies]
ring = ">=0.12.1"
rand = ">=0.4.2"
