[package]
name = "orion"
version = "0.1.3"
authors = ["brycx <brycx@protonmail.com>"]
description = "Hassle-free cryptographic function(s) in Rust."
keywords = [ "cryptography", "hmac", "hkdf" ]
readme = "README.md"
repository = "https://github.com/brycx/orion"
license = "MIT"

[dependencies]
rand = ">=0.4.2"
sha-1 = "0.7.0"
sha2 = "0.7.0"
sha3 = "0.7.2"

[dev-dependencies]
hex = "0.3.1"
