[package]
name = "orion"
version = "0.2.12"
authors = ["brycx <brycx@protonmail.com>"]
description = "Cryptographic functions implemented in Rust, with a simple API."
keywords = [ "cryptography", "hmac", "hkdf", "pbkdf" ]
categories = [ "cryptography" ]
readme = "README.md"
repository = "https://github.com/brycx/orion"
documentation = "https://docs.rs/orion"
license = "MIT"
publish = false

[dependencies]
rand = ">=0.4.2"
sha2 = ">=0.7.1"
clear_on_drop = "0.2.3"
byte-tools = "0.2.0"

[dev-dependencies]
hex = "0.3.1"

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 2
