[package]
name = "orion"
version = "0.13.4"
authors = ["brycx <brycx@protonmail.com>"]
description = "Easy and usable rust crypto"
keywords = [ "cryptography", "crypto", "aead", "hash", "mac" ]
categories = [ "cryptography", "no-std" ]
edition = "2018"
readme = "README.md"
repository = "https://github.com/brycx/orion"
documentation = "https://docs.rs/orion"
license = "MIT"
exclude = [
    ".gitignore",
    ".travis.yml",
    "benches/*",
    "fuzz/*",
    "tests/*"
]

[dependencies]
rand_os = { version = "0.1.3", optional = true }
tiny-keccak = "1.4.2"
subtle = { version = "2.0.0", default-features = false }
zeroize = { version = "0.6.0", default-features = false }

[features]
default = [ "safe_api" ]
safe_api = [ "rand_os" ]
nightly = [ "subtle/nightly", "safe_api" ]
no_std = [ "subtle/nightly" ]

[dev-dependencies]
hex = "0.3.2"
serde_json = "1.0.39"
quickcheck = "0.8.2"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3

[badges]
travis-ci = { repository = "brycx/orion", branch = "crates-published" }
codecov = { repository = "brycx/orion", branch = "crates-published" }
appveyor = { repository = "brycx/orion", branch = "crates-published" }
maintenance = { status = "actively-developed" }
