[package]
name = "orion"
version = "0.1.41"
authors = ["brycx <brycx@protonmail.com>"]
description = "Random cryptographic functions in Rust."
keywords = [ "cryptography", "hmac", "hkdf" ]
readme = "README.md"
repository = "https://github.com/brycx/orion"
license = "MIT"

[dependencies]
rand = ">=0.4.2"
sha2 = ">=0.7.0"
clear_on_drop = "0.2.3"


[dev-dependencies]
hex = "0.3.1"
