[package]
name = "orion"
version = "0.4.3"
authors = ["brycx <brycx@protonmail.com>"]
description = "Easy and usable rust crypto"
keywords = [ "cryptography", "hmac", "hkdf", "pbkdf2", "cshake" ]
categories = [ "cryptography" ]
readme = "README.md"
repository = "https://github.com/brycx/orion"
documentation = "https://docs.rs/orion"
license = "MIT"
exclude = [
    ".gitignore",
    ".travis.yml",
    "benches/*",
    "fuzz/*",
    "src/tests/*"
]

[dependencies]
rand = "0.5.5"
sha2 = "0.7.1"
tiny-keccak = "1.4.2"
clear_on_drop = "0.2.3"
byte-tools = "0.2.0"
constant_time_eq = "0.1.3"

[dev-dependencies]
hex = "0.3.2"
ring = "0.13.2"

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 3

[badges]
travis-ci = { repository = "brycx/orion" }
codecov = { repository = "brycx/orion" }
maintenance = { status = "experimental" }
